### ISSUE TITLE
Add PHP 7.1 images

### ISSUE THREAD

**Issue by tstoeckler** [drupal-docker/drush#20]
Not sure how the mix of Drush and PHP versions is handled here, but in any case would be very useful to have containers with PHP 7.1

**Comment by tstoeckler** [comment]
Oops, I didn't realize the normal php-cli containers have Drush now. Sorry for the noise.

**Comment by zaporylie** [comment]
php-cli images only have Drush Launcher (https://github.com/drush-ops/drush-launcher)
